# Generated by Django 3.0.8 on 2020-07-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
